### ISSUE TITLE
error when executng rake test command

### ISSUE THREAD

**Issue by abeatwi123** [larskanis/pg-ldap-sync#10]
psych.rb:377:in `parse': (<unknown>): did not find expected key while parsing a block mapping at line 2 column 4 (Psych::SyntaxError)
        from /db/ruby/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
        from /db/ruby/lib/ruby/2.4.0/psych.rb:325:in `parse'
        from /db/ruby/lib/ruby/2.4.0/psych.rb:252:in `load'
        from /db/ruby/lib/ruby/gems/2.4.0/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:67:in `read_config_file'
        from /db/ruby/lib/ruby/gems/2.4.0/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:309:in `start!'
        from /db/ruby/lib/ruby/gems/2.4.0/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:353:in `run'
        from /db/pg-ldap-sync-master/bin/pg_ldap_sync:6:in `<main>

**Comment by abeatwi123** [comment]
any idea what is causing that error above?

**Comment by larskanis** [comment]
pg-ladp-sync-0.2.0 has a lot of improvements to the CI test suite. It should work per:
```sh
git clone https://github.com/larskanis/pg-ldap-sync
cd pg-ldap-sync
bundle install
PATH=$PATH:/usr/lib/postgresql/10/bin/ bundle exec rake test
```
If necessary adjust the path to the postgresql bin directory.
