### ISSUE TITLE
Connect to domain forest

### ISSUE THREAD

**Issue by creativ3monster** [larskanis/pg-ldap-sync#28]
Hi guys,

first thx for this cool solution! With a single domain it is working perfect for me.
But the requirements are now to connect to a domain forest, so users are in a special domain as the groups.
I tired to connect both with two domains in the host section but that is not working.
Is there any way to do this? 
Thank You!

**Comment by larskanis** [comment]
I never worked with a domain forest. Does it require two LDAP connections to two different servers? That is not supported so far. Or does it require two different base-dn? That should work.

**Comment by creativ3monster** [comment]
Hi larskanis,

thx for your quick respond. Yes i thought i need two ldap connections but managed now to use the magic AD group memberOf:1.2.840.113556.1.4.1941: to check the others domain groups.

I have now a second question. Is there a way to exclude some users/roles? 
We have some application db users without an ad user, but we want to keep them.

**Comment by larskanis** [comment]
> I have now a second question. Is there a way to exclude some users/roles?
> We have some application db users without an ad user, but we want to keep them.

This is easy. Use [sample-config2.yaml](https://github.com/larskanis/pg-ldap-sync/blob/49a03915a77b2a2ad20215ad1a95ab2219488f63/config/sample-config2.yaml) as a basis. You need to create `ldap_user` and `ldap_group` roles manually in PostgreSQL and use the `filter:` property on PostgreSQL and LDAP ends to select only relevant roles. All other roles are untouched.
