### ISSUE TITLE
Issue while installing on redhat

### ISSUE THREAD

**Issue by vasista** [larskanis/pg-ldap-sync#29]
Hi,

pg_ldap_sync works like charm. 
we have installed then on Cent OS and we didn't face any issue but when we are doing on redhat we are facing a issue with one of the lib header. "<libpq-fe.h>".
we are using postgres version 11. and if we try to install it from postgresql-devel it shows the conflict.
Please let us know if there is any other way to install pg_ldap_sync on redhat where having postgres version 11.x.
Thanks in advance.

Thanks
Vasista

**Comment by larskanis** [comment]
The missing header file is probably related to the pg.gem (also known as ruby-pg). This gem needs the PostgreSQL client libraries to be installed. And pg_ldap_sync doesn't work without the pg.gem. The header files are usually in some package like `libpq-devel` . Did you install it?

**Comment by larskanis** [comment]
Closing since it's not an issue of pg-ldap-sync. If there are more issues with pg, please file a record in the ruby-pg project.
