### ISSUE TITLE
Large AD group causes the members to be removed from the pg-group.

### ISSUE THREAD

**Issue by ycauld** [larskanis/pg-ldap-sync#32]
A large AD from with 1501 members fails to merge the users with the pg-group.  As a result all of the members of the pg-group have their membership revoked from the pg-group.  The issue start when the three members were add to the AD group taking the number of members from 1498 to 1501.  removing the three members allows the sync to work correctly.

**Comment by johannesboon** [comment]
Probably related to: https://stackoverflow.com/questions/11984305/always-getting-1500-member-of-distribution-list-using-powershell#11984702

**Comment by larskanis** [comment]
Here's an example of how to retrieve the members in batches per ruby-net-ldap: https://github.com/ruby-ldap/ruby-net-ldap/issues/208#issue-94753667  
Something like this needs to be implemented into pg-ldap-sync [here](https://github.com/larskanis/pg-ldap-sync/blob/master/lib/pg_ldap_sync/application.rb#L110) to fix the above issue.

**Comment by lij55** [comment]
Hi @larskanis , we have the same issue. is there any plan when to fix it? we are not familiar with Ruby so we can't raise PR but we are glad to help to test if needed. thanks!

**Comment by larskanis** [comment]
Fixed by #37

**Comment by larskanis** [comment]
pg-ldap-sync-0.4.0 is released. It should support groups with more than 1500 users out of the box with no further configuration. Could you please try it out?
