### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by vasista** [larskanis/pg-ldap-sync#35]
Hi,

I hope you are doing well.
I am facing the below error when I am testing pg-ldap-sync. I have used a different ruby version but the error is the same. Please find the error below. 

-- Control frame information -----------------------------------------------
c:0010 p:---- s:0057 e:000056 CFUNC  :conninfo_parse
c:0009 p:0026 s:0052 e:000051 METHOD /home/gpadmin/.rvm/gems/ruby-2.7.2/gems/pg-1.4.1/lib/pg/connection.rb:680
c:0008 p:0007 s:0041 e:000040 METHOD /home/gpadmin/.rvm/gems/ruby-2.7.2/gems/pg-1.4.1/lib/pg/connection.rb:661
c:0007 p:0019 s:0035 e:000034 METHOD /home/gpadmin/.rvm/gems/ruby-2.7.2/gems/pg-1.4.1/lib/pg.rb:69
c:0006 p:0066 s:0029 e:000028 METHOD /home/gpadmin/.rvm/gems/ruby-2.7.2/gems/pg-ldap-sync-0.3.0/lib/pg_ldap_sync/application.rb:325
c:0005 p:0071 s:0023 E:000710 METHOD /home/gpadmin/.rvm/gems/ruby-2.7.2/gems/pg-ldap-sync-0.3.0/lib/pg_ldap_sync/application.rb:371
c:0004 p:0030 s:0017 e:000016 TOP    /home/gpadmin/.rvm/gems/ruby-2.7.2/gems/pg-ldap-sync-0.3.0/exe/pg_ldap_sync:6 [FINISH]
c:0003 p:---- s:0013 e:000012 CFUNC  :load
c:0002 p:0112 s:0008 E:000b20 EVAL   /home/gpadmin/.rvm/gems/ruby-2.7.2/bin/pg_ldap_sync:23 [FINISH]
c:0001 p:0000 s:0003 E:000770 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/home/gpadmin/.rvm/gems/ruby-2.7.2/bin/pg_ldap_sync:23:in `<main>'
/home/gpadmin/.rvm/gems/ruby-2.7.2/bin/pg_ldap_sync:23:in `load'
/home/gpadmin/.rvm/gems/ruby-2.7.2/gems/pg-ldap-sync-0.3.0/exe/pg_ldap_sync:6:in `<top (required)>'
/home/gpadmin/.rvm/gems/ruby-2.7.2/gems/pg-ldap-sync-0.3.0/lib/pg_ldap_sync/application.rb:371:in `run'
/home/gpadmin/.rvm/gems/ruby-2.7.2/gems/pg-ldap-sync-0.3.0/lib/pg_ldap_sync/application.rb:325:in `start!'
/home/gpadmin/.rvm/gems/ruby-2.7.2/gems/pg-1.4.1/lib/pg.rb:69:in `connect'
/home/gpadmin/.rvm/gems/ruby-2.7.2/gems/pg-1.4.1/lib/pg/connection.rb:661:in `new'
/home/gpadmin/.rvm/gems/ruby-2.7.2/gems/pg-1.4.1/lib/pg/connection.rb:680:in `connect_to_hosts'
/home/gpadmin/.rvm/gems/ruby-2.7.2/gems/pg-1.4.1/lib/pg/connection.rb:680:in `conninfo_parse'

-- Machine register context ------------------------------------------------
 RIP: 0x00007fbdc82468c1 RBP: 0x00000000015a15a8 RSP: 0x00007ffe37947978
 RAX: 0x0000000000000000 RBX: 0x0000000000000014 RCX: 0x0000000000000014
 RDX: 0x00000000009785c0 RDI: 0x0000000000000014 RSI: 0x00000000015a14b8
  R8: 0x0000000000000000  R9: 0x0000000000000002 R10: 0x00007fbdba72ae7d
 R11: 0x00007fbdc8264590 R12: 0x000000000154e390 R13: 0x00000000015a1b70
 R14: 0x00000000015a14b8 R15: 0x00000000014e55f0 EFL: 0x0000000000010287

-- C level backtrace information -------------------------------------------
Segmentation fault (core dumped)

************************************************************************************************************

-- Control frame information -----------------------------------------------
c:0010 p:---- s:0057 e:000056 CFUNC  :conninfo_parse
c:0009 p:0026 s:0052 e:000051 METHOD /home/gpadmin/.rvm/gems/ruby-3.0.0/gems/pg-1.4.1/lib/pg/connection.rb:680
c:0008 p:0007 s:0041 e:000040 METHOD /home/gpadmin/.rvm/gems/ruby-3.0.0/gems/pg-1.4.1/lib/pg/connection.rb:661
c:0007 p:0019 s:0035 e:000034 METHOD /home/gpadmin/.rvm/gems/ruby-3.0.0/gems/pg-1.4.1/lib/pg.rb:69
c:0006 p:0066 s:0029 e:000028 METHOD /home/gpadmin/.rvm/gems/ruby-3.0.0/gems/pg-ldap-sync-0.3.0/lib/pg_ldap_sync/application.rb:325
c:0005 p:0071 s:0023 E:001680 METHOD /home/gpadmin/.rvm/gems/ruby-3.0.0/gems/pg-ldap-sync-0.3.0/lib/pg_ldap_sync/application.rb:371
c:0004 p:0030 s:0017 e:000016 TOP    /home/gpadmin/.rvm/gems/ruby-3.0.0/gems/pg-ldap-sync-0.3.0/exe/pg_ldap_sync:6 [FINISH]
c:0003 p:---- s:0013 e:000012 CFUNC  :load
c:0002 p:0112 s:0008 E:000790 EVAL   /home/gpadmin/.rvm/gems/ruby-3.0.0/bin/pg_ldap_sync:23 [FINISH]
c:0001 p:0000 s:0003 E:002210 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/home/gpadmin/.rvm/gems/ruby-3.0.0/bin/pg_ldap_sync:23:in `<main>'
/home/gpadmin/.rvm/gems/ruby-3.0.0/bin/pg_ldap_sync:23:in `load'
/home/gpadmin/.rvm/gems/ruby-3.0.0/gems/pg-ldap-sync-0.3.0/exe/pg_ldap_sync:6:in `<top (required)>'
/home/gpadmin/.rvm/gems/ruby-3.0.0/gems/pg-ldap-sync-0.3.0/lib/pg_ldap_sync/application.rb:371:in `run'
/home/gpadmin/.rvm/gems/ruby-3.0.0/gems/pg-ldap-sync-0.3.0/lib/pg_ldap_sync/application.rb:325:in `start!'
/home/gpadmin/.rvm/gems/ruby-3.0.0/gems/pg-1.4.1/lib/pg.rb:69:in `connect'
/home/gpadmin/.rvm/gems/ruby-3.0.0/gems/pg-1.4.1/lib/pg/connection.rb:661:in `new'
/home/gpadmin/.rvm/gems/ruby-3.0.0/gems/pg-1.4.1/lib/pg/connection.rb:680:in `connect_to_hosts'
/home/gpadmin/.rvm/gems/ruby-3.0.0/gems/pg-1.4.1/lib/pg/connection.rb:680:in `conninfo_parse'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f87435528c1 RBP: 0x00000000021e89b0 RSP: 0x00007ffe0a5ec928
 RAX: 0x0000000000000000 RBX: 0x0000000000000014 RCX: 0x0000000000000014
 RDX: 0x00000000011255a0 RDI: 0x0000000000000014 RSI: 0x00000000022a51f0
  R8: 0x0000000000000000  R9: 0x0000000000000002 R10: 0x00007f8735a2d5ed
 R11: 0x00007f8743570590 R12: 0x00000000022a5420 R13: 0x00000000021e8970
 R14: 0x00000000022a51f0 R15: 0x0000000001a273c0 EFL: 0x0000000000010287

-- C level backtrace information -------------------------------------------
Segmentation fault (core dumped)

Thanks
Vasista

**Comment by larskanis** [comment]
What OS are you using? Which command do you run? How is your config file?

You might want to try

```ruby
gem pristine pg
```
in order to reinstall the pg gem.

In any case the failure is not in pg-ldap-sync but in the pg gem or the libpq.

**Comment by vasista** [comment]
I am using CentOS, 
will try to reinstall the gem and will circle back. 

Thanks
Vasista

**Comment by vasista** [comment]
it is fixed.
the issue was with pg the latest version(1.4.1) was throwing those errors.
I uninstalled pg gem and installed pg v1.2.3 and now it works. 

Thanks
Vasista
