### ISSUE TITLE
Password authentication failed

### ISSUE THREAD

**Issue by SamuelMolling** [larskanis/pg-ldap-sync#36]
Hello, my postgres user does not have a password, is it possible to make him perform the operation, without needing a password?

**Comment by johannesboon** [comment]
You mean for logging in on PostgreSQL?
That's what the login method `trust` is for I think, in hba.conf, see:

https://www.postgresql.org/docs/current/auth-pg-hba-conf.html
https://www.postgresql.org/docs/current/auth-trust.html

**Comment by SamuelMolling** [comment]
In my case i used peer for all users in all databases, but i receive this error:

**Comment by SamuelMolling** [comment]
My pg_hba

```
# Authenticate remote users via Ldap - https://www.postgresql.org/docs/current/static/auth-methods.html#AUTH-LDAP
host    all             ldap     0.0.0.0/0               ldap ldapserver="SECRET"

# Allow remote connections (we are already in a secure/private network)
host    all             all             0.0.0.0/0               md5

# Allow replication
host    replication     all             0.0.0.0/0               md5

# Allow local backup with database (jenkins)
local   replication     database                        peer

# Allow local backup with postgres
local   replication     postgres                                peer

# "local" is for Unix domain socket connections only
local   all             all                                     peer
~                                                                  
```

**Comment by larskanis** [comment]
> fe_sendauth: no password supplied (PG::ConnectionBad)

You're not using the `peer` authentication method and not the UnixSocket connection. Probably you've set the `host` parameter to something non-empty or the `PGHOST` environment variable.

**Comment by SamuelMolling** [comment]
This is my pg_ldap_sync.yaml in pg_connection section
pg_connection:
  host: localhost
  dbname: postgres
  user: postgres
  password:

**Comment by SamuelMolling** [comment]
My question was how do I not use a password, since my postgres user does not have a password, I don't know if I understood the problem/solution correctly

**Comment by johannesboon** [comment]
To use a local connection (Unix Domain Socket) you can fill the `host:` with the filename of the socket starting with a forward slash, or leave it empty, otherwise you are using TCP sockets, like Lars mentioned in https://github.com/larskanis/pg-ldap-sync/issues/36#issuecomment-1200012247

**Comment by johannesboon** [comment]
Unless you use Windows which by default connects to localhost, according to:

https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS

Probably for lacking support for https://en.wikipedia.org/wiki/Unix_domain_socket although recently Windows 10 has been extended with support for AF_UNIX - though I don't know if that will be used by PostgreSQL at this point in time

**Comment by SamuelMolling** [comment]
> > fe_sendauth: nenhuma senha fornecida (PG::ConnectionBad)
> 
> Você não está usando o `peer`método de autenticação e nem a conexão UnixSocket. Provavelmente você definiu o `host`parâmetro como algo não vazio ou a `PGHOST`variável de ambiente.

PGHOST is not defined and host parameter is null in my yaml file.

**Comment by SamuelMolling** [comment]
Now I understand, reread more calmly.

**Comment by SamuelMolling** [comment]
I'll close the issue, because I managed to solve it. Thanks
