### ISSUE TITLE
Define a ldap group filter which contains the "cn=Domain Users"

### ISSUE THREAD

**Issue by alexlopespereira** [larskanis/pg-ldap-sync#4]
Hi,

I'm using this ldap-sync. It fits exactly on my needs. I could successfully sync the users and groups. But I beliedve I did not setup correctly the ldap_groups parameters.

Here is my config file:
#############Begin of my config file##########################
ldap_connection:
  host: 192.168.0.20
  port: 389
  auth:
    method: :simple
    username: CN=Postgres SEC,OU=COMPANYLOC,OU=Users,OU=COMPANYSEC,OU=COMPANYDIR,DC=Network,DC= company,DC=com,DC=br
    password: "password"

ldap_users:
  base: OU=COMPANYDIR,DC=Network,DC= company,DC=com,DC=br
  filter: (&(objectClass=person)(objectClass=organizationalPerson)(givenName=*)(sn=*))
  name_attribute: sAMAccountName

ldap_groups:
  base: OU=COMPANYSEC,OU=COMPANYDIR,DC=Network,DC= company,DC=com,DC=br
  filter: (|(CN=loc_sec_db_read_only))
  name_attribute: cn
  member_attribute: member

pg_connection:
  host: 192.168.0.10
  dbname: postgres
  user: postgres
  password: password

pg_users:
  filter: rolcanlogin AND NOT rolsuper
  create_options: LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION

pg_groups:
  filter: NOT rolcanlogin AND NOT rolsuper
  create_options: NOLOGIN NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE NOREPLICATION
  grant_options: 
############End of my config file ################

Here is a piece of the output:
###############Begin of the output ########################
$>  pg_ldap_sync -c ./config_sync_ldap.yaml -vv
I, [2016-01-13T10:04:36.184535 #11232]  INFO -- : user stat: create: 0 drop: 0 keep: 645
I, [2016-01-13T10:04:36.184589 #11232]  INFO -- : group stat: create: 1 drop: 0 keep: 0
W, [2016-01-13T10:04:36.185454 #11232]  WARN -- : ldap member with dn CN=Domain Users,CN=Users,DC=Network,DC= company,DC=com,DC=br is unknown
I, [2016-01-13T10:04:36.186076 #11232]  INFO -- : membership stat: grant: 1 revoke: 0 keep: 0
I, [2016-01-13T10:04:36.187874 #11232]  INFO -- : SQL: CREATE ROLE "loc_sec_db_read_only" NOLOGIN NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE NOREPLICATION
I, [2016-01-13T10:04:36.192699 #11232]  INFO -- : SQL: GRANT "loc_sec_db_read_only" TO "foo.user" 
#########################End of the output #########################

I created a group called loc_sec_db_read_only. Then I added the Active Directory "cn=Domain Users" to it. And for testing purpose I added the user foo.user to the same group.

What happened is that the pg_ldap_sync application granted the role loc_sec_db_read_only to foo.user but not to the users inside Domain Users.

It is quite simple to understand why it didn't work: searching in loc_sec_db_read_only for the objects members (member_attribute: member) will, of course (see the ldapsearch query bellow), return these two objects. 

In my point of view, adding all current members to loc_sec_db_read_only group is not suitable because we'll need to manually add every new users to it.

So, the question is: how can I setup the parameters in order to the pg_ldap_sync application search the Domain Users inside loc_sec_db_read_only ?

Thank you very much.
Alex Lopes Pereira

################Begin of ldapsearch output ##########################
$ ldapsearch -h 192.168.0.20 -p 389 -x -b "cn=loc_sec_db_read_only,OU=Groups,OU=CRPV,OU=CENSIPAM,DC=Rede,DC=sipam,DC=gov,DC=br" -D "CN=Postgres SEC,OU=COMPANYLOC,OU=Users,OU=COMPANYSEC,OU=COMPANYDIR,DC=Network,DC= company,DC=com,DC=br" -W
Enter LDAP Password: 
 # extended LDIF
 # LDAPv3
 # base <cn=loc_sec_db_read_only,OU=Groups,OU=COMPANYSEC,OU=COMPANYDIR,DC=Network,DC= company,DC=com,DC=br> with scope subtree
 # filter: (objectclass=*)
 # requesting: ALL

 # loc_sec_db_read_only, Groups, SEC, COMPANYDIR, 192.168.0.20
dn: CN=loc_sec_db_read_only,OU=Groups,OU=COMPANYSEC,OU=COMPANYDIR,DC=Network,DC= company,DC=com,DC=br
objectClass: top
objectClass: group
cn: loc_sec_db_read_only
member: CN=Foo User,OU=COINT,OU=Users,OU=CRBE,OU=COMPANYDIR,DC=Network,DC= company,DC=com,DC=br
member: CN=Domain Users,CN=Users,DC=Network,DC= company,DC=com,DC=br
distinguishedName: CN=loc_sec_db_read_only,OU=Groups,OU=COMPANYSEC,OU=COMPANYDIR,DC=Network,DC= company,DC=com,DC=br
instanceType: 4
whenCreated: 20160112151212.0Z
whenChanged: 20160113000204.0Z
uSNCreated: 4172211
uSNChanged: 4176677
name: loc_sec_db_read_only
objectGUID:: 2fjZgyQZf0CI0heyiF4Flw==
objectSid:: AQUAAAAAAAUVAAAA7CYBtuwuaN3HhXsd0xIAAA==
sAMAccountName: loc_sec_db_read_only
sAMAccountType: 536870912
groupType: -2147483644
objectCategory: CN=Group,CN=Schema,CN=Configuration,DC=Network,DC= company,DC=com,DC=br
dSCorePropagationData: 16010101000000.0Z

 # search result
search: 2
result: 0 Success

 # numResponses: 2
 # numEntries: 1
##################End of ldapsearch output ####################

**Comment by larskanis** [comment]
Did you have a look at the second sample config:
https://github.com/larskanis/pg-ldap-sync/blob/master/config/sample-config2.yaml

This is the configuration we use in production. This separates ldap rules
by a special postgres group.

--
Regards, Lars

**Comment by alexlopespereira** [comment]
Hi Lars,

You did helped me. I had seen it, but I thought the sample-config.yaml was the right choice to me.
Here is my settings in case any ldap newbie (like me) needs to sync to postgres.

The points I was missing were:
ldap_groups:
  filter: (&(objectClass=group)) ###this filter selects all groups from OU=COMPANYSEC
...
pg_users:
  filter: oid IN (SELECT pam.member FROM pg_auth_members pam JOIN pg_roles pr ON pr.oid=pam.roleid WHERE pr.rolname='ldap_users')
  create_options: LOGIN IN ROLE ldap_users ### this is a group manually created on postgres
...
pg_groups:
  filter: oid IN (SELECT pam.member FROM pg_auth_members pam JOIN pg_roles pr ON pr.oid=pam.roleid WHERE pr.rolname='ldap_groups')
  create_options:  NOLOGIN IN ROLE ldap_groups ### this is a group manually created on postgres

Thank you very much for the application and the help.
Alex Lopes Pereira

#############Begin of my config file##########################
ldap_connection:
  host: 192.168.0.20
  port: 389
  auth:
    method: :simple
    username: CN=Postgres SEC,OU=COMPANYLOC,OU=Users,OU=COMPANYSEC,OU=COMPANYDIR,DC=Network,DC= company,DC=com,DC=br
    password: "password"

ldap_users:
  base: OU=COMPANYDIR,DC=Network,DC= company,DC=com,DC=br
  filter: (&(objectClass=person)(objectClass=organizationalPerson)(givenName=*)(sn=*))
  name_attribute: sAMAccountName

ldap_groups:
  base: OU=COMPANYSEC,OU=COMPANYDIR,DC=Network,DC= company,DC=com,DC=br
  filter: (&(objectClass=group)) ###this filter selects all groups from OU=COMPANYSEC
  name_attribute: cn
  member_attribute: member

pg_connection:
  host: 192.168.0.10
  dbname: postgres
  user: postgres
  password: password

pg_users:
  filter: oid IN (SELECT pam.member FROM pg_auth_members pam JOIN pg_roles pr ON pr.oid=pam.roleid WHERE pr.rolname='ldap_users')
  create_options: LOGIN IN ROLE ldap_users

pg_groups:
  filter: oid IN (SELECT pam.member FROM pg_auth_members pam JOIN pg_roles pr ON pr.oid=pam.roleid WHERE pr.rolname='ldap_groups')
  create_options:  NOLOGIN IN ROLE ldap_groups
  grant_options: 
############End of my config file ################

**Comment by larskanis** [comment]
One additional note: you can use @ldap_users in your pg_hba file, to define
the authentication methods of the ldap users (in case they are different to
ordinary users).

Thanks for following up!

**Comment by brianr-dk** [comment]
I know this issue is way old - but it looks as if you fought with the same as I did. 
I can't figure what I do wrong here - but if possible, can you see from details here where my mistake lies? 

```
I've had an OU created where I can play around. 
In that I've created two group, and made two user accounts member in the admin one. readonly is empty. 
Users will not replicate into postgres with the following configuration.

What am I missing here, is it my 'filter' that are plain wrong? 



----------------------------------------------------------------------
AD configuration overview: 

OU=POSTGRES_AD_SYNC_TEST   (OU=POSTGRES_AD_SYNC_TEST,OU=Dept,OU=Securitygroup,DC=domain,DC=name)
	Group CN=postgres_test_admin
			member: user1
			member: user2
	Group CN=postgres_test_readonly
			member: [none]


Excerpts from my config file inspired from your    sample-config2.yaml 
----------------------------------------------------------------------
ldap_users:
  base: OU=POSTGRES_AD_SYNC_TEST,OU=Dept,OU=Securitygroup,DC=domain,DC=name
  filter: (&(objectClass=person)(objectClass=organizationalPerson)(givenName=*)(sn=*)(sAMAccountName=*))
  name_attribute: sAMAccountName
  lowercase_name: true
  bothcase_name: false
 
# Search parameters for LDAP groups which should be synchronized
ldap_groups:
  base: OU=POSTGRES_AD_SYNC_TEST,OU=Dept,OU=Securitygroup,DC=domain,DC=name
  # Didnt work: 
  #filter: (cn=*)
  filter: (&(ObjectClass=Group))
  # this attribute is used as PG role name
  name_attribute: cn
  # lowercase name for use as PG role name
  lowercase_name: false
  # this attribute must reference to all member DN's of the given group
  member_attribute: member
  
----------------------------------------------------------------------
pg-ldap-sync result  - SO close to the goal, and then not :) : 

Test: 
pg_ldap_sync -c pg_ldap_sync.yaml -vv -t
I, [2025-01-09T11:34:29.911504 #14624]  INFO -- : found group-dn: CN=postgres_test_admin,,OU=Dept,OU=Securitygroup,DC=domain,DC=name
I, [2025-01-09T11:34:29.912112 #14624]  INFO -- : found group-dn: CN=postgres_test_readonly,,OU=Dept,OU=Securitygroup,DC=domain,DC=name
I, [2025-01-09T11:34:29.987090 #14624]  INFO -- : found pg-group: "postgres_test_admin" with members: []        (This is probebly pg-ldap-sync finding the previously imported group?)
I, [2025-01-09T11:34:29.988052 #14624]  INFO -- : found pg-group: "postgres_test_readonly" with members: []     (This is probebly pg-ldap-sync finding the previously imported group?)
I, [2025-01-09T11:34:29.990680 #14624]  INFO -- : user stat: create: 0 drop: 0 keep: 0
I, [2025-01-09T11:34:29.990863 #14624]  INFO -- : group stat: create: 0 drop: 0 keep: 2
W, [2025-01-09T11:34:29.992031 #14624]  WARN -- : ldap member with dn CN=user1,OU=Dept,OU=TopDept,OU=MoretopDept,OU=Users,DC=domain,DC=name       is unknown  (Why is that?)
W, [2025-01-09T11:34:29.992420 #14624]  WARN -- : ldap member with dn CN=user2,OU=Dept,OU=SomePGAdmins,OU=Admins,DC=domain,DC=name                is unknown  (Why is that?) 
I, [2025-01-09T11:34:29.993204 #14624]  INFO -- : membership stat: grant: 0 revoke: 0 keep: 0

```

**Comment by alexlopespereira** [comment]
Hi,

I do not work with this for a long time. I don’t remember the details. I
guess I’m not helpful anymore.

Att,
Alex

**Comment by brianr-dk** [comment]
Thanks for responding, Alex. 
I was actually also rather hoping to catch the eye of @larskanis  - I'm sure he could dig right down to my error, probably similar to yours ;)

**Comment by larskanis** [comment]
`ldap member with dn CN=user1,OU=Dept,OU=TopDept,OU=MoretopDept,OU=Users,DC=domain,DC=name       is unknown` 

Means that this user was recognized as a member of a group retrieved from the ldap groups query, but the ldap query for users didn't retrieve this user. So the user filter is too strict. At least one of the conditions is not satisfied.

**Comment by brianr-dk** [comment]
Ah, that's a good explanation. Thanks once again!

Is the ldap_users search recursive, because I have the same 'base:' value for both groups/users, pointing the the "root"of where I'm allowed to mess around in AD. 
My hope was that it would then find all groups from there and the members in those. 


But I can't seem to "catch" those users with any filter.  (I managed to get the meaning of (%(searchcondition1)(searchcondition2))   and tried to simply have a    filter:(sAMAccount=*) 
( I even left out the filter:, which you know the consequence of :D )

Do I simply *need* to point to the groups it must find ldap_users in? (I hope not), 
or is there a flag to "search recursive from base:"  

I hope it does not matter, that the members/users are in a completely other 'location' (dn?) in our AD, or must their location be part of the search filter ... ?

**Comment by brianr-dk** [comment]
Oh! 

Now it makes sense. (well ... or more-ish sense :) ) 
ldap must have been fun to develop. 

**Thanks** for your patience, Lars!

**Comment by brianr-dk** [comment]
And it was a **success**! 

I think I assumed blindly that if users were members in a group catched by base: / filter: , then the details would be present to the script for users object too. 

However, it would seem that I need to ask for either redesign of my AD then, if my **base:** must be something that includes all. 
Or my **filter:** should then be a mix of "|" and "&" - in order to catch all the places in AD, where someone is placed that needs access to a specific database. 

Without **filter:**, my postgres will subsequently contain a ROLES for each and every user in the universe (if my AD covers that space)? 

Thanks for your clarifications - MUST appreciated. I have spent too much time trying to understand and make this ldap work.
