### ISSUE TITLE
Install pg-ldap-sync offline

### ISSUE THREAD

**Issue by Farzanah1808** [larskanis/pg-ldap-sync#8]
Hello, 

I have downloaded the pg-ldap-sync.git using wget in command line.

While installing it, I am having the following errors: 

Command for Installing :  git clone pg-ldap-sync.git /opt/pg-ldap-sync/

Output
Cloning into '/opt/pg-ldap-sync'...
fatal: Invalid gitfile format: /opt/rpm_repo/pg-ldap-sync.git
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
> git clone pg-ldap-sync.git pg-ldap-sync
Cloning into 'pg-ldap-sync'...
fatal: Invalid gitfile format: /opt/rpm_repo/pg-ldap-sync.git
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Any idea why am having this issue?

Thank You,
Regards
Farzanah

**Comment by larskanis** [comment]
I guess, git can't access the downloaded files to be cloned.

You could however download the gem files directly from https://rubygems.org:
```gem fetch pg kwalify net-ldap pg-ldap-sync```
and install them offline:
```gem install -l pg kwalify net-ldap pg-ldap-sync```

For more convenience with dependent gems, ```bunder package``` can be used.

**Comment by Farzanah1808** [comment]
Hello,

Thank You.

Regards,
Farzanah

**Comment by Farzanah1808** [comment]
Hello,
   
    when i have done 
      - gem install -l pg kwalify net-ldap pg-ldap-sync
      no folder pg-ldap-sync was created. i have downloaded the pg-ldap-sync and copy and paste the folder in a specific folder.

   when i run pg_ldap_sync -c test.yaml -vv -t
  
  i am getting /home/spoon/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- pg (LoadError)
        from /home/spoon/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/spoon/.rvm/gems/ruby-2.1.8/gems/pg-ldap-sync-0.1.1/lib/pg_ldap_sync/application.rb:11:in `<top (required)>'
        from /home/spoon/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/spoon/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/spoon/.rvm/gems/ruby-2.1.8/gems/pg-ldap-sync-0.1.1/bin/pg_ldap_sync:4:in `<top (required)>'
        from /home/spoon/.rvm/gems/ruby-2.1.8/bin/pg_ldap_sync:23:in `load'
        from /home/spoon/.rvm/gems/ruby-2.1.8/bin/pg_ldap_sync:23:in `<main>'
   
can you please help?

thanks
Regards
Farazanah

**Comment by Farzanah1808** [comment]
Hello,
  
   i have been able to solve the issues. ( missing postgresql-devel)

  thanks
Regards
Farazanah
